server.port: 8081


spring.datasource.url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName: org.h2.Driver
spring.datasource.username: sa
spring.datasource.password: password
spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

spring:
  threads:
    corePoolSize: 10
    maxPoolSize: 20
    queueCapacity: 10000
spring.h2.console.enabled: true

cloud:
  aws:
    stack:
      auto: false
    sns:
      topic:
        # Change the AWS topic
        topicName: topic-name
    region:
      auto: false
      static: us-west-2
    credentials:
      instanceProfile: true
      # Change the account Id for the AWS
      accountId: account-id

server.shutdown.grace-period: 30s

logging:
  level:
    root: ERROR
    com.sample.application.demo: DEBUG
    org.hibernate.SQL: INFO
    com.amazonaws: DEBUG
    org.springframework.boot.web.embedded.tomcat: INFO
